language: csharp
solution: GitBack.sln
install:
  - nuget restore GitBack.sln
script:
  - xbuild /p:Configuration=Release GitBack.sln
  - mono ./packages/xunit.runner.console.2.1.0/tools/xunit.console.exe ./GitBack.Tests/bin/Release/GitBack.Tests.dll